language: node_js
node_js:
  - "6"
script:
  - npm run test
after_script:"sudo npm install -g istanbul && istanbul cover && npm install coveralls && cat coverage.lcov | ../node_modules/coveralls/bin/coveralls.js"
branches:
  only:
    - master
